In [1]:
import numpy as np

arr1 = np.arange(0, 10, 2)
print("Array using arange:", arr1)



import numpy as np

# linspace(): Create evenly spaced values between two limits
arr2 = np.linspace(0, 1, 5)

print("Array using linspace:", arr2)

Array using arange: [0 2 4 6 8]
Array using linspace: [0.   0.25 0.5  0.75 1.  ]


In [2]:
import numpy as np
arr3 = np.arange(1, 10).reshape((3, 3))

print("Reshaped Array (3x3):\n", arr3)

print("Flattened version:", arr3.flatten())

Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [3]:
import numpy as np


data = np.array([
    [5, 8, 9],
    [2, 4, 6]
])

print("Original Data:\n", data)

Original Data:
 [[5 8 9]
 [2 4 6]]


In [4]:
print("Sum of all elements:", np.sum(data))
print("Column-wise sum:", np.sum(data, axis=0))
print("Row-wise mean:", np.mean(data, axis=1))
print("Max value:", np.max(data))



Sum of all elements: 34
Column-wise sum: [ 7 12 15]
Row-wise mean: [7.33333333 4.        ]
Max value: 9
